### ISSUE TITLE
How can i use your API in front POST?

### ISSUE THREAD

**Issue by Ihavesoul** [aichbauer/express-rest-api-boilerplate#15]
Hi guys. Thank you very much for good job. It's very good API. 
But i'm a noob in FrontEnd and can't understand how i can use your API.
I mean.
First question : What different between /public and /private?
Second : i have code in my VUE client
```js
import axios from 'axios';
export default {
  data () {
    return {
        form: {
        username: '',
        password: '',
      },
    }
  },
 methods: {
    onSubmit (evt) {
      evt.preventDefault()
      // this.$router.push('/home')
    axios.post(`http://localhost:3003/api/login`, this.form)
    .then(response => {
      // JSON responses are automatically parsed.
      this.form = response.data
      sessionStorage.setItem('token',response.data.token);
      this.$router.push('/home')
    })
    .catch(e => {
      console.log(e)
    })
    }
  }
```
And i have troubles only with Login. Auth service work good.
What i have to do for use your api? Can't understand.
Sry for my noobs qust. And thank you for listening.
P.S. and ofc. sry for bad eng, from Russia.

**Comment by aichbauer** [comment]
Hey 😄 

thank you for your interest in this project.

> First question : What different between /public and /private?

* routes under `/private` needs an authentication header with `{"Authorization": "Bearer <token>"}`
* routes under `/public` do not need an auth header

> Second : i have code in my VUE client And i have troubles only with Login. Auth service work good. What i have to do for use your api? Can't understand.

to use login route use `http://localhost:2017/public/login` if you use the standart port from this api

all routes are declared in the `/config/routes` folder - take a look at the routes

here the `publicRoutes.js`
```js
{
  'POST /login': 'UserController.login',
}
```
this route means you need to make a `post` request to `/public/login` and the function on `UserController.login` gets called

here the `privateRoutes.js`
```js
{
  'GET /users': 'UserController.getAll',
};
```
this route means you need to make a `get` request to `/private/users` and the function on `UserController.getAll` gets called, and since this is a private route you need to provide an auth header with `{"Authorization": "Bearer <token>"}`

No problem, if you need further questions, do not hesitate to ask...

**Comment by aichbauer** [comment]
So I don't know how your Vue app works, but as I see you work with axios you could add your header as thrid argument...

```
axios.get('http://localhost:8080/private/users', {
    headers: { Authorization: 'JWT ' + token }
}).then((res)=> ...)
```

the error message you are receiving is correct... since you try to login with username and password, the api login is with email and password

```
axios.post('http://localhost:8080/public/login', {
      email: 'test@mail.com',
      password: 'yourpassword'
}).then((res)=> ...)
```

you do not have to encyrpt you password client side...

**Comment by Ihavesoul** [comment]
Big thanks! Thank you very much!)

**Comment by Ihavesoul** [comment]
Rly how i can't see what i post username..but not email..

**Comment by aichbauer** [comment]
i do not really understand the question...


but you are using here the username as key for the data you post to the server... you should change username to email, but maybe you have to change something in your app somewhere else too...
```js
 data () {
    return {
        form: {
        username: '',
        password: '',
      },
    }
  },
```

**Comment by Ihavesoul** [comment]
Dude, you helped me very much when I answered the second time) I want to close the question, but did not understand how. Sorry.
I did everything, everything works fine, thank you very much)
