### ISSUE TITLE
JWTService.verify is not a function

### ISSUE THREAD

**Issue by Ihavesoul** [aichbauer/express-rest-api-boilerplate#17]
Hi. It's again me : DDD
Am..idk. I don't touch this files. But when i want to /get : /private/users
I have a error : JWTService.verify is not a function

Ofc i save my bearer token, and i test valid this token in /public/validate.

I test this in POSTMAN, and this is doesn't work. 
Thanks for help .

**Comment by aichbauer** [comment]
Hey 😃

I think the problem is that in the `auth.policy` file we use `JWTService.verify` but it has to be `JWTService().verify` as the `authService` is a function...

let me know if that works...

**Comment by Ihavesoul** [comment]
It works  : D
wow. Thanks.

And i have another qst while you are here : D
when i register user, server get me a Bearer token . And this token save in Headers? Just when i use
public/validate i should past my token in some field , but not in header. But, it's okay. I understand this is just for test, i think.

Annd.. now : D . When i register my user, where i should save my user?
Probably i think about sessions . I think this can be worked?

Sorry if I already got you.

**Comment by aichbauer** [comment]
Nice, would you mind creating a PR to fix this issue in this repository? That would help me a lot 👍 

For your second question:

you may have a application store, like redux or similar... or you could use the local storage... 

most of the time when people talk about sessions, they mean server side sessions...  maybe that is what you meant...  
and JWT is just a way to handle a session of a use on the client instead of handling a session of a user on the server... 

so **you** have to implement when a user has to re-autheticate, when a users session should end... 

The "safest" (there are always more secure ways 😬, but there is also no right or wrong, its what suits your needs, or better what suits the needs of your users) way is to just store the users JWT for the lifetime of the application...

 you also can adjust the `expiresIn` of the JWT...  Right now its set to 10800 seconds which is exactly 3 hours... maybe you want a jwt to be valid for a longer duration, maybe it should be shorter... it is up to you... And to not forget to use a new secret for your app when you are in production... right now its pretty unsecure... 

```js
const secret = process.env.NODE_ENV === 'production' ? process.env.JWT_SECRET : 'secret';
``` 

so when you start your app in production you should add a `JWT_SECRET=<super_secure_hash_value_level_over_9000>`

the best source to learn about JWT is on [https://jwt.io/](https://jwt.io/)...

**Comment by Ihavesoul** [comment]
Thank you very much.
Yes, i creating PR or create branch (sry, idk how it's works in GitHub) when i create client for your app + jwt storage.
Or you mean fix JWT().verify? If you talk about this - sure. )
Thanks for link, i should read this.)

**Comment by aichbauer** [comment]
I mean the to fix `JWT().verify` if that works... Here is a good description on how to open a [PR](https://github.com/aichbauer/express-rest-api-boilerplate/blob/master/CONTRIBUTING.md#open-a-pull-request) if you want a more detailed information on how to contribute to open source , [Kent C. Dodds](https://twitter.com/kentcdodds) has a good [tutorial](http://makeapullrequest.com/)

**Comment by ace3** [comment]
hi, thank you for making this boilerplate. 

i tried to contribute by doing what you requested.

thanks.

**Comment by ace3** [comment]
hi @aichbauer ,
i make a non standart PR. 

i will create a new PR to help.
