### ISSUE TITLE
New table not created as per the model

### ISSUE THREAD

**Issue by curiousPup** [aichbauer/express-rest-api-boilerplate#36]
the table for a new defined model is not getting created the way it is generated for User model

**Comment by ace3** [comment]
@curiousPup , do you mean the model generated by sequelize-cli is different from the example user model ?

**Comment by aichbauer** [comment]
@curiousPup if you create a new model and you have set `migrate: true` in https://github.com/aichbauer/express-rest-api-boilerplate/blob/c8f088bbaf3fc96f225902b20a385f4d5a716df6/config/index.js#L5

then you have to manually add the table in the database or you set `migrate: false` then the complete database will be dropped (do not do that in production) and then the database will be set up with the new table (model) in place, but without any data....

Tell me if that is what you needed to know. Otherwise, we'll need more information about what you are trying to achieve...

**Comment by curiousPup** [comment]
migrate is set to false, but adding a new model is not even generaing the empty table

**Comment by aichbauer** [comment]
It is pretty much impossible to help you without seeing any of your code...

**Comment by aichbauer** [comment]
closed due to no response
